"""The landing page, in every language the app speaks.

VERSION is written here rather than fetched by the page. A visitor should not
have to wait on api.github.com, and a version number that only appears when a
request succeeds is worse than one that is simply true at build time.

It is written by `.github/workflows/release.yml`, which rewrites this line, runs
build-site.py and pushes the result after it publishes a release. It said so
before that was true, and the site sat on 1.0.0 through the whole of 1.1.0
because nothing anywhere actually did it.
"""

VERSION = "1.6.1"

L = {}

L["en"] = {
    "downloads": "Downloads",
    "releases": "Releases",
    "days": "Days of Belay",
    "appstore_count": "App Store",
    "direct_count": "Direct",
    "since_note": "since {date}",
    "title": "Keep your Mac awake while AI coding agents work – Belay",
    "meta": "A free menu bar app that keeps your Mac awake while Claude Code, Codex, Cline and Copilot work – not caffeinate, but a power layer for local AI agents on macOS.",
    "h1": "Keeps your Mac awake <br class=\"turn\">while your AI agents work.",
    "lede": "Belay keeps your Mac awake while a coding agent is working. When the work stops, Belay gets out of the way and your Mac can sleep normally again.",
    "body": "Built-in detection for Claude Code, Codex, Cline and Copilot CLI, plus one-click presets for Gemini CLI, OpenCode, Aider and Pi. You can also point Belay at a folder for anything else. Detection stays on your Mac. No account. No telemetry. Belay never sends your prompts or code anywhere.",
    "modes_head": "Your agents, at a glance",
    "gallery_back": "Previous",
    "gallery_next": "Next",
    "gallery_dot": "Screen {n}",
    "modes_auto": "Holds only while an agent is working.",
    "modes_always": "Holds until you switch it back.",
    "modes_off": "Never holds. Belay just watches.",
    "appstore": "Download on the App Store",
    "appstore_top": "Download on the",
    "appstore_name": "App Store",
    "support_head": "Helping out",
    "support_body": "Belay is free, and the code is open. If it saved you a run, a star on GitHub costs nothing and helps other people find it. Bug reports and translations are worth more than money.",
    "donate": "Donate",
    "sponsor": "Sponsor on GitHub",
    "star": "Star on GitHub",
    "more": "How it works",
    "download": "Download for macOS",
    "source": "Source Code",
    "free": "Free & open code.",
    "version": "Version {version}",
    "notes": "Release notes",
    "roadmap": "Roadmap",
    "privacy": "Privacy policy",
    "licence": "Free, never for sale",
    "trademarks": "All product names and logos are trademarks of their respective owners.",
    "bug": "Report a bug",
    "language": "Language",
}

L["ru"] = {
    "downloads": "Скачиваний",
    "releases": "Релизов",
    "days": "Дней Belay",
    "appstore_count": "App Store",
    "direct_count": "Напрямую",
    "since_note": "с {date}",
    "title": "Не даёт Mac уснуть, пока работают AI-агенты – Belay",
    "meta": "Бесплатное приложение в строке меню: Mac не спит, пока работают Claude Code, Codex, Cline и Copilot. Не caffeinate, а слой питания для локальных AI-агентов.",
    "h1": "Mac не заснёт, <br class=\"turn\">пока AI-агенты работают.",
    "lede": "Belay не даст вашему Mac уснуть, пока агенты работают. Как только все агенты завершат работу, Belay переведёт Mac в обычный режим засыпания.",
    "body": "Автоматическое определение Claude Code, Codex, Cline и Copilot CLI, а также пресеты в один клик для Gemini CLI, OpenCode, Aider и Pi. Для других агентов можно указать папку работы. Без регистрации, смс и телеметрии. Belay не читает и никуда не отправляет ваши сессии.",
    "modes_head": "Ваши агенты – с одного взгляда",
    "gallery_back": "Назад",
    "gallery_next": "Вперёд",
    "gallery_dot": "Экран {n}",
    "modes_auto": "Держит, только пока агент работает.",
    "modes_always": "Держит, пока не переключите обратно.",
    "modes_off": "Не держит никогда. Belay просто смотрит.",
    "appstore": "Загрузить в App Store",
    "appstore_top": "Скачать с",
    "appstore_name": "App Store",
    "support_head": "Поддержать проект",
    "support_body": "Belay бесплатный, и его код открыт. Если он помог вам, оставьте звезду на GitHub, помогите другим найти его. Котику на корм? Архитектору крылья? Welcome!",
    "donate": "Поддержать",
    "sponsor": "Спонсировать на GitHub",
    "star": "Оценить на GitHub",
    "more": "Как это работает",
    "download": "Скачать для macOS",
    "source": "Исходный код",
    "free": "Бесплатно, код открыт.",
    "version": "Версия {version}",
    "notes": "Последние релизы",
    "roadmap": "Дорожная карта",
    "privacy": "Конфиденциальность",
    "licence": "Бесплатно и не продаётся",
    "trademarks": "Все названия продуктов и логотипы являются товарными знаками их правообладателей.",
    "bug": "Сообщить об ошибке",
    "language": "Язык",
}

L["de"] = {
    "downloads": "Downloads",
    "releases": "Versionen",
    "days": "Tage Belay",
    "appstore_count": "App Store",
    "direct_count": "Direkt",
    "since_note": "seit {date}",
    "title": "Mac wach halten, solange KI-Agenten arbeiten – Belay",
    "meta": "Kostenlose Menüleisten-App: hält den Mac wach, während Claude Code, Codex, Cline und Copilot arbeiten – kein caffeinate, eine Power-Schicht für lokale KI-Agenten.",
    "h1": "Bleibt wach, solange deine Agenten arbeiten.",
    "lede": "Belay hält deinen Mac wach, solange ein Coding-Agent arbeitet. Hört die Arbeit auf, geht Belay aus dem Weg und dein Mac kann wieder normal schlafen.",
    "body": "Eingebaute Erkennung für Claude Code, Codex, Cline und Copilot CLI, dazu Ein-Klick-Vorlagen für Gemini CLI, OpenCode, Aider und Pi. Für alles andere kannst du Belay auf einen Ordner richten. Die Erkennung bleibt auf deinem Mac. Kein Konto. Keine Telemetrie. Belay schickt deine Prompts und deinen Code nirgendwohin.",
    "modes_head": "Deine Agenten auf einen Blick",
    "gallery_back": "Zurück",
    "gallery_next": "Weiter",
    "gallery_dot": "Ansicht {n}",
    "modes_auto": "Hält nur, solange ein Agent arbeitet.",
    "modes_always": "Hält, bis du zurückschaltest.",
    "modes_off": "Hält nie. Belay schaut nur zu.",
    "appstore": "Im App Store laden",
    "appstore_top": "Laden im",
    "appstore_name": "App Store",
    "support_head": "Mithelfen",
    "support_body": "Belay ist kostenlos, und der Code ist offen. Wenn es dir einen Lauf gerettet hat: ein Stern auf GitHub kostet nichts und hilft anderen, es zu finden. Fehlerberichte und Übersetzungen sind mehr wert als Geld.",
    "donate": "Spenden",
    "sponsor": "Auf GitHub sponsern",
    "star": "Stern auf GitHub",
    "more": "Wie es funktioniert",
    "download": "Für macOS laden",
    "source": "Quellcode",
    "free": "Kostenlos, offener Code.",
    "version": "Version {version}",
    "notes": "Versionshinweise",
    "roadmap": "Roadmap",
    "privacy": "Datenschutz",
    "licence": "Kostenlos und unverkäuflich",
    "trademarks": "Alle Produktnamen und Logos sind Marken ihrer jeweiligen Inhaber.",
    "bug": "Fehler melden",
    "language": "Sprache",
}

L["es"] = {
    "downloads": "Descargas",
    "releases": "Versiones",
    "days": "Días de Belay",
    "appstore_count": "App Store",
    "direct_count": "Directo",
    "since_note": "desde {date}",
    "title": "Mantén el Mac despierto mientras trabajan tus agentes IA",
    "meta": "App gratuita de barra de menús: el Mac no duerme mientras trabajan Claude Code, Codex, Cline y Copilot – no es caffeinate, es una capa de energía para agentes de IA.",
    "h1": "Despierto mientras trabajan tus agentes.",
    "lede": "Belay mantiene tu Mac despierto mientras un agente está trabajando. Cuando el trabajo termina, Belay se aparta y tu Mac vuelve a dormir con normalidad.",
    "body": "Detección integrada para Claude Code, Codex, Cline y Copilot CLI, más ajustes preparados de un clic para Gemini CLI, OpenCode, Aider y Pi. Para lo demás, puedes indicarle una carpeta. La detección se queda en tu Mac. Sin cuenta. Sin telemetría. Belay no envía tus prompts ni tu código a ninguna parte.",
    "modes_head": "Tus agentes, de un vistazo",
    "gallery_back": "Anterior",
    "gallery_next": "Siguiente",
    "gallery_dot": "Pantalla {n}",
    "modes_auto": "Solo mantiene despierto mientras un agente trabaja.",
    "modes_always": "Mantiene despierto hasta que lo cambies.",
    "modes_off": "No mantiene nada. Belay solo observa.",
    "appstore": "Descargar en el App Store",
    "appstore_top": "Descargar en el",
    "appstore_name": "App Store",
    "support_head": "Cómo ayudar",
    "support_body": "Belay es gratis y su código está abierto. Si te salvó una ejecución, una estrella en GitHub no cuesta nada y ayuda a que otros lo encuentren. Los informes de errores y las traducciones valen más que el dinero.",
    "donate": "Donar",
    "sponsor": "Patrocinar en GitHub",
    "star": "Estrella en GitHub",
    "more": "Cómo funciona",
    "download": "Descargar para macOS",
    "source": "Código fuente",
    "free": "Gratis, código abierto a la vista.",
    "version": "Versión {version}",
    "notes": "Notas de la versión",
    "roadmap": "Hoja de ruta",
    "privacy": "Privacidad",
    "licence": "Gratis y nunca a la venta",
    "trademarks": "Todos los nombres de productos y logotipos son marcas comerciales de sus respectivos propietarios.",
    "bug": "Informar de un error",
    "language": "Idioma",
}

L["fr"] = {
    "downloads": "Téléchargements",
    "releases": "Versions",
    "days": "Jours de Belay",
    "appstore_count": "App Store",
    "direct_count": "Direct",
    "since_note": "depuis {date}",
    "title": "Gardez le Mac éveillé quand vos agents IA travaillent",
    "meta": "App gratuite : garde votre Mac éveillé pendant que Claude Code, Codex, Cline et Copilot travaillent – pas un caffeinate, une couche d'énergie pour les agents IA locaux.",
    "h1": "Éveillé pendant que vos agents travaillent.",
    "lede": "Belay garde votre Mac éveillé pendant qu'un agent travaille. Quand le travail s'arrête, Belay s'efface et votre Mac peut de nouveau dormir normalement.",
    "body": "Détection intégrée pour Claude Code, Codex, Cline et Copilot CLI, plus des préréglages en un clic pour Gemini CLI, OpenCode, Aider et Pi. Pour le reste, vous pouvez désigner un dossier. La détection reste sur votre Mac. Pas de compte. Pas de télémétrie. Belay n'envoie vos prompts et votre code nulle part.",
    "modes_head": "Vos agents, en un coup d'œil",
    "gallery_back": "Précédent",
    "gallery_next": "Suivant",
    "gallery_dot": "Écran {n}",
    "modes_auto": "Ne retient que pendant qu'un agent travaille.",
    "modes_always": "Retient jusqu'à ce que vous reveniez en arrière.",
    "modes_off": "Ne retient jamais. Belay se contente de regarder.",
    "appstore": "Télécharger dans l'App Store",
    "appstore_top": "Télécharger dans",
    "appstore_name": "l'App Store",
    "support_head": "Donner un coup de main",
    "support_body": "Belay est gratuit, et son code est ouvert. S'il vous a sauvé une exécution, une étoile sur GitHub ne coûte rien et aide les autres à le trouver. Les rapports de bugs et les traductions valent plus que l'argent.",
    "donate": "Faire un don",
    "sponsor": "Sponsoriser sur GitHub",
    "star": "Étoile sur GitHub",
    "more": "Comment ça marche",
    "download": "Télécharger pour Mac",
    "source": "Code source",
    "free": "Gratuit, code ouvert.",
    "version": "Version {version}",
    "notes": "Notes de version",
    "roadmap": "Feuille de route",
    "privacy": "Confidentialité",
    "licence": "Gratuit, jamais à vendre",
    "trademarks": "Tous les noms de produits et logos sont des marques de leurs propriétaires respectifs.",
    "bug": "Signaler un bug",
    "language": "Langue",
}

L["it"] = {
    "downloads": "Download",
    "releases": "Versioni",
    "days": "Giorni di Belay",
    "appstore_count": "App Store",
    "direct_count": "Diretto",
    "since_note": "dal {date}",
    "title": "Tieni sveglio il Mac mentre lavorano gli agenti IA – Belay",
    "meta": "App gratuita nella barra dei menu: il Mac resta sveglio mentre lavorano Claude Code, Codex, Cline e Copilot – non caffeinate, uno strato di energia per gli agenti IA.",
    "h1": "Sveglio mentre i tuoi agenti lavorano.",
    "lede": "Belay tiene sveglio il Mac mentre un agente sta lavorando. Quando il lavoro finisce, Belay si toglie di mezzo e il Mac può tornare a dormire normalmente.",
    "body": "Rilevamento integrato per Claude Code, Codex, Cline e Copilot CLI, più preset con un clic per Gemini CLI, OpenCode, Aider e Pi. Per tutto il resto puoi indicargli una cartella. Il rilevamento resta sul tuo Mac. Nessun account. Nessuna telemetria. Belay non manda da nessuna parte i tuoi prompt o il tuo codice.",
    "modes_head": "I tuoi agenti, in un colpo d'occhio",
    "gallery_back": "Precedente",
    "gallery_next": "Successivo",
    "gallery_dot": "Schermata {n}",
    "modes_auto": "Tiene sveglio solo mentre un agente lavora.",
    "modes_always": "Tiene sveglio finché non torni indietro.",
    "modes_off": "Non tiene mai. Belay si limita a guardare.",
    "appstore": "Scarica sull'App Store",
    "appstore_top": "Scarica su",
    "appstore_name": "App Store",
    "support_head": "Dare una mano",
    "support_body": "Belay è gratis e il codice è aperto. Se ti ha salvato un'esecuzione, una stella su GitHub non costa nulla e aiuta gli altri a trovarlo. Le segnalazioni di bug e le traduzioni valgono più dei soldi.",
    "donate": "Dona",
    "sponsor": "Sponsorizza su GitHub",
    "star": "Stella su GitHub",
    "more": "Come funziona",
    "download": "Scarica per macOS",
    "source": "Codice sorgente",
    "free": "Gratis, codice aperto.",
    "version": "Versione {version}",
    "notes": "Note di versione",
    "roadmap": "Roadmap",
    "privacy": "Privacy",
    "licence": "Gratuito e mai in vendita",
    "trademarks": "Tutti i nomi di prodotto e i loghi sono marchi dei rispettivi proprietari.",
    "bug": "Segnala un bug",
    "language": "Lingua",
}

L["zh"] = {
    "downloads": "下载量",
    "releases": "版本",
    "days": "Belay 天数",
    "appstore_count": "App Store",
    "direct_count": "直接下载",
    "since_note": "自 {date}",
    "title": "AI 编程智能体工作时让 Mac 保持唤醒 – Belay",
    "meta": "免费菜单栏应用：Claude Code、Codex、Cline 和 Copilot 工作时让 Mac 保持唤醒。它不是 caffeinate，而是 macOS 上本地 AI 智能体的电源层。",
    "h1": "智能体在工作，Mac 就不会睡。",
    "lede": "编程智能体工作时，Belay 让你的 Mac 保持唤醒。工作一停，Belay 就退到一边，Mac 照常进入睡眠。",
    "body": "内置 Claude Code、Codex、Cline 与 Copilot CLI 检测，另有 Gemini CLI、OpenCode、Aider 和 Pi 的一键预设。其他智能体可以指定一个工作文件夹。检测只在你的 Mac 上进行。无需注册，没有遥测。Belay 不会把你的提示词或代码发送到任何地方。",
    "modes_head": "你的智能体，一眼尽览",
    "gallery_back": "上一张",
    "gallery_next": "下一张",
    "gallery_dot": "第 {n} 张",
    "modes_auto": "仅在智能体工作时保持唤醒。",
    "modes_always": "一直保持唤醒，直到你切换回来。",
    "modes_off": "从不保持唤醒，Belay 只是监视。",
    "appstore": "在 App Store 下载",
    "appstore_top": "下载",
    "appstore_name": "App Store",
    "support_head": "搭把手",
    "support_body": "Belay 免费，代码公开。如果它保住了你的一次运行，在 GitHub 上加个星标不花什么，也能帮别人找到它。错误报告和翻译比钱更有价值。",
    "donate": "捐赠",
    "sponsor": "在 GitHub 上赞助",
    "star": "在 GitHub 上加星标",
    "more": "工作原理",
    "download": "下载 macOS 版",
    "source": "源代码",
    "free": "免费，代码公开。",
    "version": "版本 {version}",
    "notes": "版本说明",
    "roadmap": "路线图",
    "privacy": "隐私政策",
    "licence": "免费，永不出售",
    "trademarks": "所有产品名称和标志均为其各自所有者的商标。",
    "bug": "报告问题",
    "language": "语言",
}
