import Foundation

/// The words the Codex app puts on the two things Belay reads by name. Codex
/// speaks the language of the Mac, so each is known in all of them. Taken
/// from Codex 26.917 on 30 September 2026; a wording that changes is a button
/// not found, and nothing is pressed.
public enum CodexWords {
    /// The button that says yes to this one request and nothing beyond it.
    public static let allowOnce: Set<String> = [
        "Allow once",
        "አንድ ጊዜ ፍቀድ",
        "السماح مرة واحدة",
        "Разреши веднъж",
        "একবার অনুমোদন করুন",
        "Dozvoli jednom",
        "Permet una vegada",
        "Povolit jednou",
        "Tillad én gang",
        "Einmal zulassen",
        "Να επιτραπεί μία φορά",
        "Permitir una vez",
        "Luba üks kord",
        "فقط این بار اجازه بده",
        "Salli kerran",
        "Autoriser une fois",
        "એકવાર મંજૂરી આપો",
        "एक बार अनुमति दें",
        "Dopusti jednom",
        "Egyszeri engedélyezés",
        "Թույլատրել մեկ անգամ",
        "Izinkan sekali",
        "Leyfa einu sinni",
        "Consenti una volta",
        "一度だけ許可",
        "ერთხელ დაშვება",
        "Бір рет рұқсат ету",
        "ಒಮ್ಮೆ ಮಾತ್ರ ಅನುಮತಿಸಿ",
        "한 번만 허용",
        "Leisti vieną kartą",
        "Atļaut vienreiz",
        "Дозволи еднаш",
        "ഒരിക്കൽ മാത്രം അനുവദിക്കുക",
        "Нэг удаа зөвшөөрөх",
        "एकदाच अनुमती द्या",
        "Benarkan sekali",
        "တစ်ကြိမ်သာ ခွင့်ပြုရန်",
        "Tillat én gang",
        "Eenmalig toestaan",
        "ਇੱਕ ਵਾਰ ਇਜਾਜ਼ਤ ਦਿਓ",
        "Zezwól raz",
        "Permitir uma vez",
        "Permite o dată",
        "Разрешить один раз",
        "Povoliť raz",
        "Dovoli enkrat",
        "Hal mar oggolow",
        "Lejo një herë",
        "Дозволи једном",
        "Tillåt en gång",
        "Ruhusu mara moja",
        "ஒருமுறை அனுமதி",
        "ఒక్కసారి అనుమతించు",
        "อนุญาตครั้งเดียว",
        "Payagan nang isang beses",
        "Bir kez izin ver",
        "Дозволити один раз",
        "ایک بار اجازت دیں",
        "Cho phép một lần",
        "允许一次",
        "允許一次"
    ]

    /// The mark on a session in the list that waits for an approval.
    public static let awaitingApproval: Set<String> = [
        "Awaiting approval",
        "መጽደቅን በመጠባበቅ ላይ",
        "في انتظار الموافقة",
        "Очаква одобрение",
        "অনুমোদনের অপেক্ষায় আছে",
        "Odobrenje na čekanju",
        "Esperant aprovació",
        "Čeká na schválení",
        "Afventer godkendelse",
        "Genehmigung ausstehend",
        "Αναμονή για έγκριση",
        "En espera de aprobación",
        "A la espera de aprobación",
        "Heakskiidu ootel",
        "در انتظار تأیید",
        "Odottaa hyväksyntää",
        "Approbation en attente",
        "En attente d’approbation",
        "મંજૂરીની રાહ જોઈ રહ્યા છીએ",
        "मंज़ूरी का इंतज़ार है",
        "Čeka odobrenje",
        "Jóváhagyásra vár",
        "Սպասում է հաստատման",
        "Menunggu persetujuan",
        "Bíður eftir samþykki",
        "In attesa di approvazione",
        "承認が必要",
        "დამტკიცების მოლოდინში",
        "Мақұлдауды күтуде",
        "ಅಪ್ರೂವಲ್ ಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
        "승인 대기 중",
        "Laukiama patvirtinimo",
        "Gaida apstiprinājumu",
        "Се чека одобрување",
        "അംഗീകാരത്തിനായി കാത്തിരിക്കുന്നു",
        "Зөвшөөрөл хүлээж байна",
        "मंजुरीची वाट बघत आहे",
        "Menunggu kelulusan",
        "ခွင့်ပြုချက်ကို စောင့်ဆိုင်းနေသည်",
        "Venter på godkjenning",
        "Wachten op goedkeuring",
        "ਮਨਜ਼ੂਰੀ ਦੀ ਉਡੀਕ ਵਿੱਚ",
        "Oczekiwanie na zatwierdzenie",
        "Aguardando aprovação",
        "A aguardar aprovação",
        "Se așteaptă aprobarea",
        "Ожидает одобрения",
        "Čaká na schválenie",
        "Čaka na odobritev",
        "Sugaya oggolaanshaha",
        "Duke pritur miratimin",
        "Чека се одобрење",
        "Väntar på godkännande",
        "Inasubiri idhini",
        "ஒப்புதலுக்காகக் காத்திருக்கிறது",
        "ఆమోదం కోసం వేచి ఉంది",
        "รอการอนุมัติ",
        "Naghihintay ng pag-apruba",
        "Onay bekleniyor",
        "Очікує схвалення",
        "منظوری کا انتظار ہے",
        "Đang chờ phê duyệt",
        "等待批准",
        "正在等待核准"
    ]
}
